[phases.setup]
nixPkgs = ["python311", "gcc", "stdenv.cc.cc.lib"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.fileWatcherType=none"

[variables]
LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:/nix/store/gcc/lib"